services:
  app:
    image: wilde67/hello-docker-app
  server:
    build: ./server
    ports: 
      - 5050:5000
    command: npm run dev
    volumes: # connect to re build on modifications === sync
      - ./server/src/:/app/src/
  mongodb:
    image: mongo
    volumes: # persist data
      - ./data:/data/db 
  client:
    build: ./client
    ports: 
      - 8080:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    command: npm start
    volumes:
      - ./client/src/:/app/src/